version: '2'
services:
    entiacbalsamiq-app:
        image: entiacbalsamiq
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://entiacbalsamiq-mysql:3306/entiacbalsamiq?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    entiacbalsamiq-mysql:
        extends:
            file: mysql.yml
            service: entiacbalsamiq-mysql
